
package master.data;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Utkarsh
 */
public class TableFrame extends javax.swing.JFrame {
    
    private DatabaseOperations dbo;
    private ArrayList<Holder> hs = new ArrayList<Holder>();
    private ArrayList<HolderTeacher> ht = new ArrayList<HolderTeacher>();
    public TableFrame() {
        dbo = new DatabaseOperations();
        initComponents();
        clearTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Tab2SemCombo1 = new javax.swing.JComboBox<>();
        Tab2SemCombo2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Tab3SemCombo = new javax.swing.JComboBox<>();
        Tab3SubCombo = new javax.swing.JComboBox<>();
        Tab3SubName = new javax.swing.JLabel();
        Tab3FacName = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        addMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Results Analysis");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Branch", "Exam Form", "Pass", "ATKT", "Fail", "Passin %"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(45);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(45);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(45);
            jTable1.getColumnModel().getColumn(1).setMinWidth(300);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(300);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Sumary", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "<HTML>Sr.<BR/>No.</HTML>", "<HTML>Student<BR/>Name</HTML>", "<HTML>Sub 1<BR/>(TH)</HTML>", "<HTML>Sub 1<BR/>(PR)</HTML>", "<HTML>Sub 2<BR/>(TH)</HTML>", "<HTML>Sub 2<BR/>(PR)</HTML>", "<HTML>Sub 3<BR/>(TH)</HTML>", "<HTML>Sub 3<BR/>(PR)</HTML>", "<HTML>Sub 4<BR/>(TH)</HTML>", "<HTML>Sub 5<BR/>(TH)</HTML>", "<HTML>Total<BR/>Obtained</HTML>", "<HTML>Result<BR/>Pass/Fail</HTML>", "<HTML>Percent</HTML>", "<HTML>SGPA</HTML>"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(45);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setPreferredWidth(125);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
            jTable2.getColumnModel().getColumn(7).setResizable(false);
            jTable2.getColumnModel().getColumn(8).setResizable(false);
            jTable2.getColumnModel().getColumn(9).setResizable(false);
            jTable2.getColumnModel().getColumn(10).setResizable(false);
            jTable2.getColumnModel().getColumn(11).setResizable(false);
            jTable2.getColumnModel().getColumn(12).setResizable(false);
            jTable2.getColumnModel().getColumn(13).setResizable(false);
        }

        Tab2SemCombo1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Tab2SemCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Branch" }));
        Tab2SemCombo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Tab2SemCombo1ItemStateChanged(evt);
            }
        });

        Tab2SemCombo2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Tab2SemCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester", "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6", "Semester 7", "Semester 8" }));
        Tab2SemCombo2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Tab2SemCombo2ItemStateChanged(evt);
            }
        });
        Tab2SemCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab2SemCombo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tab2SemCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(339, 339, 339))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(Tab2SemCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(694, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Tab2SemCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(Tab2SemCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(488, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Semester wise", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr. No.", "Student Name", "Marks Obtained", "Total Marks", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMinWidth(100);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable3.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable3.getColumnModel().getColumn(1).setMinWidth(300);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable3.getColumnModel().getColumn(1).setMaxWidth(300);
            jTable3.getColumnModel().getColumn(2).setMinWidth(200);
            jTable3.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable3.getColumnModel().getColumn(2).setMaxWidth(200);
            jTable3.getColumnModel().getColumn(3).setMinWidth(200);
            jTable3.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTable3.getColumnModel().getColumn(3).setMaxWidth(200);
            jTable3.getColumnModel().getColumn(4).setMinWidth(200);
            jTable3.getColumnModel().getColumn(4).setPreferredWidth(200);
            jTable3.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        Tab3SemCombo.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Tab3SemCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Semester", "Semester 1", "Semester 2", "Semester 3", "Semester 4", "Semester 5", "Semester 6", "Semester 7", "Semester 8" }));
        Tab3SemCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Tab3SemComboItemStateChanged(evt);
            }
        });
        Tab3SemCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab3SemComboActionPerformed(evt);
            }
        });

        Tab3SubCombo.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Tab3SubCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subject" }));
        Tab3SubCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Tab3SubComboItemStateChanged(evt);
            }
        });
        Tab3SubCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tab3SubComboActionPerformed(evt);
            }
        });

        Tab3SubName.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Tab3SubName.setText("Subject Name");

        Tab3FacName.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        Tab3FacName.setText("Subject Faculty Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(Tab3SemCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(Tab3SubCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Tab3SubName)
                    .addComponent(Tab3FacName))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tab3SemCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tab3SubCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tab3SubName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Tab3FacName)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jTabbedPane2.addTab("Subject wise", jPanel3);

        addMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/master/data/add.png"))); // NOI18N
        addMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(addMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMenuMouseClicked
        System.out.println("Add menu!");
        InputFrame iff = new InputFrame();
        iff.setLocationRelativeTo(null);
        iff.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        iff.setVisible(true);
    }//GEN-LAST:event_addMenuMouseClicked

    private void Tab3SemComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Tab3SemComboItemStateChanged
        int sel = Tab3SemCombo.getSelectedIndex();
        String sem1[][] = {{"s1s1", "s1s2", "s1s3", "s1s4", "s1s5"},
                            {"s2s1", "s2s2", "s2s3", "s2s4", "s2s5"},
                            {"s3s1", "s3s2", "s3s3", "s3s4", "s3s5"},
                            {"s4s1", "s4s2", "s4s3", "s4s4", "s4s5"},
                            {"s5s1", "s5s2", "s5s3", "s5s4", "s5s5"},
                            {"s6s1", "s6s2", "s6s3", "s6s4", "s6s5"},
                            {"s7s1", "s7s2", "s7s3", "s7s4", "s7s5"},
                            {"s8s1", "s8s2", "s8s3", "s8s4", "s8s5"}};
        DefaultComboBoxModel model;
        switch(sel){
            case 1: Tab3SubCombo.removeAllItems();
                    model = new DefaultComboBoxModel( sem1[sel-1] );
                    Tab3SubCombo.setModel( model );
                    break;
            case 2: Tab3SubCombo.removeAllItems();
                    model = new DefaultComboBoxModel( sem1[sel-1] );
                    Tab3SubCombo.setModel( model );
                    break;
            case 3: Tab3SubCombo.removeAllItems();
                    model = new DefaultComboBoxModel( sem1[sel-1] );
                    Tab3SubCombo.setModel( model );
                    break;
            case 4: Tab3SubCombo.removeAllItems();
                    model = new DefaultComboBoxModel( sem1[sel-1] );
                    Tab3SubCombo.setModel( model );
                    break;
            case 5: Tab3SubCombo.removeAllItems();
                    model = new DefaultComboBoxModel( sem1[sel-1] );
                    Tab3SubCombo.setModel( model );
                    break;
            case 6: Tab3SubCombo.removeAllItems();
                    model = new DefaultComboBoxModel( sem1[sel-1] );
                    Tab3SubCombo.setModel( model );
                    break;
            case 7: Tab3SubCombo.removeAllItems();
                    model = new DefaultComboBoxModel( sem1[sel-1] );
                    Tab3SubCombo.setModel( model );
                    break;
            case 8: Tab3SubCombo.removeAllItems();
                    model = new DefaultComboBoxModel( sem1[sel-1] );
                    Tab3SubCombo.setModel( model );
                    break;
            default: Tab3SubCombo.removeAllItems();
                     Tab3SubCombo.addItem("Select subject");
                     break;
        }
    }//GEN-LAST:event_Tab3SemComboItemStateChanged

    private void Tab3SemComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab3SemComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tab3SemComboActionPerformed

    private void Tab2SemCombo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Tab2SemCombo1ItemStateChanged
        clearTables();
        setTable2();
    }//GEN-LAST:event_Tab2SemCombo1ItemStateChanged

    private void Tab2SemCombo2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Tab2SemCombo2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Tab2SemCombo2ItemStateChanged

    private void Tab3SubComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab3SubComboActionPerformed
        //setTable3();
    }//GEN-LAST:event_Tab3SubComboActionPerformed

    private void Tab3SubComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Tab3SubComboItemStateChanged
        clearTables();
        setTable3();
    }//GEN-LAST:event_Tab3SubComboItemStateChanged

    private void Tab2SemCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tab2SemCombo2ActionPerformed
        clearTables();
        setTable2();
    }//GEN-LAST:event_Tab2SemCombo2ActionPerformed

    public void clearTables(){
        DefaultTableModel table1 = (DefaultTableModel) jTable1.getModel();
        DefaultTableModel table2 = (DefaultTableModel) jTable2.getModel();
        DefaultTableModel table3 = (DefaultTableModel) jTable3.getModel();
        table1.setRowCount(0);
        table2.setRowCount(0);
        table3.setRowCount(0);
        setTables();
    }
    
    public void setTables(){
        String query = "Select Count(*) from Student "+
                       "Where Atkt = 'y' OR Atkt = 'y';";
        int atkt = dbo.directQuery(query);
        System.out.println("Atkt:"+atkt);
        
        query = "Select Count(*) from Student "+
                "Where Result = 'pass' OR Atkt = 'Pass';";
        int pass = dbo.directQuery(query);
        System.out.println("Pass: " + pass);
        
        query = "Select Count(*) from Student "+
                "Where Result = 'fail' OR Atkt = 'Fail';";
        int fail = dbo.directQuery(query);
        System.out.println("Fail: " + fail);
        
        int total = pass + fail + atkt;
        
        float percent = ((float)(pass + atkt)/(float)total) * 100.0f;
        
        System.out.println("Percent: " + percent);
        DefaultTableModel tablemod = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSelectionAllowed(true);
        jTable1.setColumnSelectionAllowed(false);
        
        for(int i=0; i<1; i++){
                tablemod.addRow(new Object[]{i+1, "xxxx", 'y', pass, atkt, fail, 98.23});
        }
    }
    
    public void setTable2(){
        int sem = Tab2SemCombo2.getSelectedIndex();
        int sub = Tab2SemCombo1.getSelectedIndex()+1;
        
        String query = "Select * from Student "+
                       "Where sem = '"+sem+"';";
        hs = dbo.directQueryStudent(query);
        
        DefaultTableModel tablemod = (DefaultTableModel) jTable2.getModel();
        jTable2.setRowSelectionAllowed(true);
        jTable2.setColumnSelectionAllowed(false);
        
        for(int i=0; i<hs.size(); i++){
                tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS1(), hs.get(i).getP1(), 
                                                  hs.get(i).getS2(), hs.get(i).getP2(),
                                                  hs.get(i).getS3(), hs.get(i).getP3(), 
                                                  hs.get(i).getS4(), hs.get(i).getS5(), 
                                                  hs.get(i).getTotal(), hs.get(i).getResult(), hs.get(i).getPercent(),
                                                  hs.get(i).getSgpa()});
        }
    }
    
    public void setTable3(){
        int sem = Tab3SemCombo.getSelectedIndex();
        int sub = Tab3SubCombo.getSelectedIndex()+1;
        String query = "Select * from Student "+
                       "Where sem = '"+sem+"';";
        hs = dbo.directQueryStudent(query);
        
        DefaultTableModel tablemod = (DefaultTableModel) jTable3.getModel();
        jTable3.setRowSelectionAllowed(true);
        jTable3.setColumnSelectionAllowed(false);
        
        query = "Select * from teacher "+
                "Where sem = '"+sem+"';";
        ht = dbo.directQueryTeacher(query);
        int flag=0;
        //System.out.println(ht.get(0).getS1() + " " + ht.get(0).getF1());
        for(int i=0; i<hs.size(); i++){
            if(sub==1){
                if(hs.get(i).getS1()>=40)
                    tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS1(), 100, "Pass"});
                else
                    tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS1(), 100, "Fail"});
                if(flag==0 && ht.size()!=0){
                    Tab3SubName.setText("Subject: " + ht.get(0).getS1());
                    Tab3FacName.setText("Faculty: " + ht.get(0).getF1());
                    flag=1;
                }
            }else if(sub==2){
                if(hs.get(i).getS2()>=40)
                    tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS2(), 100, "Pass"});
                else
                    tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS2(), 100, "Fail"});
                if(flag==0 && ht.size()!=0){
                    Tab3SubName.setText("Subject: " + ht.get(0).getS2());
                    Tab3FacName.setText("Faculty: " + ht.get(0).getF2());
                    flag=1;
                }
            }else if(sub==3){
                if(hs.get(i).getS3()>=40)
                    tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS3(), 100, "Pass"});
                else
                    tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS3(), 100, "Fail"});
                if(flag==0 && ht.size()!=0){
                    Tab3SubName.setText("Subject: " + ht.get(0).getS3());
                    Tab3FacName.setText("Faculty: " + ht.get(0).getF3());
                    flag=1;
                }
            }else if(sub==4){
                if(hs.get(i).getS4()>=40)
                    tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS4(), 100, "Pass"});
                else
                    tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS4(), 100, "Fail"});
                if(flag==0 && ht.size()!=0){
                    Tab3SubName.setText("Subject: " + ht.get(0).getS4());
                    Tab3FacName.setText("Faculty: " + ht.get(0).getF4());
                    flag=1;
                }
            }else if(sub==5){
                if(hs.get(i).getS5()>=40)
                    tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS5(), 100, "Pass"});
                else
                    tablemod.addRow(new Object[]{i+1, hs.get(i).getName(), hs.get(i).getS5(), 100, "Fail"});
                if(flag==0 && ht.size()!=0){
                    Tab3SubName.setText("Subject: " + ht.get(0).getS5());
                    Tab3FacName.setText("Faculty: " + ht.get(0).getF5());
                    flag=1;
                }
            }    
        }
    }
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Tab2SemCombo1;
    private javax.swing.JComboBox<String> Tab2SemCombo2;
    private javax.swing.JLabel Tab3FacName;
    private javax.swing.JComboBox<String> Tab3SemCombo;
    private javax.swing.JComboBox<String> Tab3SubCombo;
    private javax.swing.JLabel Tab3SubName;
    private javax.swing.JMenu addMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
